# This file was generated by GoReleaser. DO NOT EDIT.
cask "ardoqcli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "592f46b53220b69cbb9a22cb9ec258272ba26a5ec37d9da51d9511b73d60a95d"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c77bc971256d535d20ccbf1df01275dae7ca202ca415f86242a055b59d3900d"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f9942db446c3fbace08d9f809f9c2cc29d857c72385adadc41ccc869de83d28"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dbbb8a64c9bd31d6496eaebc98e663b2b5e1a4a3e41605d727e8fa0ab7fdf12"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ardoqcli"
  desc "CLI for Ardoq REST API v2"
  homepage "https://github.com/samyukti/ardoq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ardoqcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ardoqcli"]
    end
  end

  # No zap stanza required

end
