# This file was generated by GoReleaser. DO NOT EDIT.
cask "ardoqcli" do
  name "ardoqcli"
  desc "CLI for Ardoq REST API v2"
  homepage "https://github.com/samyukti/ardoq"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ardoqcli"

  on_macos do
    on_intel do
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_amd64.tar.gz"
      sha256 "d4c0472d204788398dd9ca26ab76bff9d693b34f006f2c62498f57ac77c0356d"
    end
    on_arm do
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_arm64.tar.gz"
      sha256 "6489c329a763776ba71b26093ab61edec8ed42f739a4bd6c9fdf7e8fee388176"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_amd64.tar.gz"
      sha256 "5cd1456679ad1007575b3ce20f9658d67a12214d921024b74def8a244f4c4df3"
    end
    on_arm do
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_arm64.tar.gz"
      sha256 "d37571902eff210babaa411440aabb92f11c59825add58cff4baf16c484c41b7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ardoqcli"]
    end
  end

  # No zap stanza required
end
