# This file was generated by GoReleaser. DO NOT EDIT.
cask "ardoqcli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b107795d3a9587fc8382526e06a7df3baf90703937a60ddea2d244edd7d6e575"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31530b27a9a87c4bf9814040abe25c24f1a3200a3fb48dc4d9959058b0b49496"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60a5e400279e31946267395909b34ba02bbd0468decebaa97d426a322ef64a96"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b0ad39b316e03f7acb65ec050b2ebb27906ae1206b4efc108fe493a8ee400e7"
      url "https://github.com/samyukti/ardoqcli/releases/download/v#{version}/ardoqcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ardoqcli"
  desc "CLI for Ardoq REST API v2"
  homepage "https://github.com/samyukti/ardoq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ardoqcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ardoqcli"]
    end
  end

  # No zap stanza required

end
