# This file was generated by GoReleaser. DO NOT EDIT.
cask "verf" do
  version "0.1.0"

  on_macos do
    sha256 "9efe600866f17bcb8f57d3912e6753215d0ae43dc8991bd176de4097bd1c5a12"
    url "https://github.com/samyukti/verf/releases/download/v#{version}/verf_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "d6f010048b31e34e740fdb5c6e6f6c222964aa37a7fe7a2145193644f5c12f81"
      url "https://github.com/samyukti/verf/releases/download/v#{version}/verf_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b4e122fd246647d6c867e92c867f232b815f59802838e84bcd00d19c8732b7f"
      url "https://github.com/samyukti/verf/releases/download/v#{version}/verf_#{version}_linux_amd64.tar.gz"
    end
  end

  name "verf"
  desc "Text-first technical diagrams on D2, styled by pluggable design systems."
  homepage "https://github.com/samyukti/verf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verf"

  # No zap stanza required
end
